services:
  api:
    build: .
    container_name: shortener-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_healthy
      celery_beat:
        condition: service_healthy

    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: shortener_postgres
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
      
  redis:
    image: redis:7-alpine
    container_name: shortener_redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  celery_worker:
    build: .
    container_name: shortener_celery_worker
    command: uv run celery -A src.core.celery_config.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "uv", "run", "celery", "-A", "src.core.celery_config.celery_app", "inspect", "ping", "--timeout", "5"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  celery_beat:
    build: .
    container_name: shortener_celery_beat
    env_file:
      - .env
    command: uv run celery -A src.core.celery_config.celery_app beat --loglevel=info --pidfile=/tmp/celery_beat.pid
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "kill -0 $(cat /tmp/celery_beat.pid 2>/dev/null) 2>/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s


volumes:
  postgres_data:
  redis_data: